import GradientScreen from '@/components/ui/GradientScreen';
import ScreenHeader from '@/components/ui/ScreenHeader';
import { useTheme } from '@/contexts/ThemeContext';
import { spacing } from '@/lib/theme';
import AsyncStorage from '@react-native-async-storage/async-storage';
import { useRouter } from 'expo-router';
import React, { useEffect, useMemo } from 'react';
import {
  BackHandler,
  ScrollView,
  StyleSheet,
  Text,
} from 'react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';

export default function TermsAndConditions() {
  const router = useRouter();
  const { colors } = useTheme();
  const styles = useMemo(() => makeStyles(colors), [colors]);

  const handleBackConfirm = async () => {
    try {
      const token = await AsyncStorage.getItem('AUTH_TOKEN');
      if (token) {
        router.replace('/home');
      } else {
        router.replace('/');
      }
    } catch (_) {
      router.replace('/');
    }
  };

  useEffect(() => {
    const sub = BackHandler.addEventListener('hardwareBackPress', () => {
      handleBackConfirm();
      return true;
    });
    return () => sub.remove();
  }, []);

  const insets = useSafeAreaInsets();

  return (
    <GradientScreen>
      <ScreenHeader title="Terms & Conditions" onBack={handleBackConfirm} />
      <ScrollView
        contentContainerStyle={[styles.content, { paddingBottom: insets.bottom + 40 }]}
        showsVerticalScrollIndicator={false}
      >
        <Text style={styles.title}>Terms and Conditions</Text>

        <Text style={styles.paragraph}>
          These Terms and Conditions govern your use of our platform (&quot;App&quot;) developed and maintained by S3BGlobal Technologies LLP. By accessing or using our services, you agree to be bound by these Terms.
        </Text>

        <Text style={styles.sectionTitle}>1. Use of Services</Text>

        <Text style={styles.paragraph}>
          You confirm that you are at least 18 years of age. Access to our services is strictly prohibited for individuals under 18.
        </Text>

        <Text style={styles.paragraph}>
          You agree to provide accurate and complete information when registering or entering personal data on the App.
        </Text>

        <Text style={styles.paragraph}>
          AI Disclaimer: All astrological readings, chat interactions, and the profiles of astrologers (including names, images, and personas) are generated by an Artificial Intelligence (AI) model and not by human experts. These outputs are provided solely for entertainment and informational purposes.
        </Text>

        <Text style={styles.paragraph}>
          No Professional Advice: The service does not provide legal, medical, financial, or other professional advice. You agree not to rely on the App as a substitute for consultation with qualified professionals.
        </Text>

        <Text style={styles.paragraph}>
          Device Compatibility: We do not guarantee that the App will function uninterrupted or error-free on all devices, operating systems, or Android versions.
        </Text>

        <Text style={styles.sectionTitle}>1.1 AI Safety & Content Reporting</Text>

        <Text style={styles.paragraph}>
          You acknowledge that AI-generated content may occasionally be inaccurate, incomplete, or inappropriate. We are committed to user safety and comply with Google Play’s AI-Generated Content policies.
        </Text>
        <Text style={styles.paragraph}>
          Reporting Mechanism: Use the in-app “Thumbs Down” or reporting features to flag any offensive, harmful, misleading, or sexually explicit content generated during chats.
        </Text>
        <Text style={styles.paragraph}>
          Zero Tolerance: All reported content is actively reviewed. Any AI outputs found to violate our safety standards are filtered, and the underlying models are updated to prevent recurrence.
        </Text>
        <Text style={styles.paragraph}>
          User Conduct: You must not intentionally prompt the AI to generate illegal, abusive, hateful, or sexually explicit content. Any such misuse may result in immediate suspension or permanent termination of your account.
        </Text>

        <Text style={styles.sectionTitle}>2. Payments, Billing and Refunds</Text>

        <Text style={styles.paragraph}>
          Free Access: We may offer 1 free question as a promotional feature. We reserve the right to modify, suspend, or discontinue this offer at any time without prior notice.
        </Text>

        <Text style={styles.paragraph}>
          Paid Services: Continued usage beyond any free allowance requires the purchase of chat credits via in-app purchases.
        </Text>

        <Text style={styles.paragraph}>
          Payment Processing: All payments are processed securely through the Google Play Store billing system. We do not collect or store your credit card, debit card, or banking details.
        </Text>

        <Text style={styles.paragraph}>
          Refunds: Sales are generally final. Refunds may be considered in limited cases of technical failure (such as non-delivery of purchased credits). All refund requests are subject to Google Play’s Refund Policy and applicable laws.
        </Text>

        <Text style={styles.sectionTitle}>3. User Responsibilities</Text>

        <Text style={styles.paragraph}>
          You are responsible for maintaining the confidentiality of your account credentials and for all activities conducted through your account.
        </Text>

        <Text style={styles.paragraph}>
          You agree not to engage in unlawful, abusive, deceptive, or harmful behavior while using the App.
        </Text>

        <Text style={styles.paragraph}>
          You must not attempt to hack, reverse-engineer, interfere with, or disrupt the App, its servers, or related systems.
        </Text>

        <Text style={styles.paragraph}>
          Third-Party Data: If you provide personal data of any third party (including a minor) for an astrological reading, you warrant that you have obtained all necessary legal permissions and consents. You agree to indemnify and hold harmless S3BGlobal Technologies LLP against any claims arising from unauthorized data sharing.
        </Text>

        <Text style={styles.sectionTitle}>4. Limitation of Liability</Text>

        <Text style={styles.paragraph}>
          The App and its services are provided on an “as-is” and “as-available” basis, without warranties of any kind. To the maximum extent permitted by law, we shall not be liable for any indirect, incidental, special, or consequential damages arising from your use of the App or reliance on AI-generated content.
        </Text>

        <Text style={styles.sectionTitle}>5. Intellectual Property</Text>

        <Text style={styles.paragraph}>
          All rights, title, and interest in the App, including its software, design, content, and AI-generated outputs, are owned exclusively by S3BGlobal Technologies LLP.
        </Text>

        <Text style={styles.paragraph}>
          You are granted a limited, non-transferable, non-commercial license to use the App in accordance with these Terms.
        </Text>

        <Text style={styles.paragraph}>
          You may not copy, reproduce, modify, distribute, or exploit any part of the App without prior written permission.
        </Text>

        <Text style={styles.sectionTitle}>6. Termination of Services</Text>

        <Text style={styles.paragraph}>
          We reserve the right to suspend or terminate your access to the App, and to delete your account and associated data, at any time if you violate these Terms or misuse the service.
        </Text>

        <Text style={styles.sectionTitle}>7. Governing Law</Text>

        <Text style={styles.paragraph}>
          These Terms are governed by and construed in accordance with the laws of India. Any disputes shall be subject to the exclusive jurisdiction of the courts located in Gurugram, Haryana.
        </Text>

        <Text style={styles.sectionTitle}>8. Contact Information</Text>

        <Text style={styles.paragraph}>
          For questions or concerns regarding these Terms, please contact us at
        </Text>

        <Text style={styles.email}>
          support@kundlitime.com
        </Text>

        <Text style={styles.sectionTitle}>9. Changes to Terms</Text>

        <Text style={styles.paragraph}>
          We reserve the right to update or modify these Terms at any time. Continued use of the App after any changes constitutes your acceptance of the revised Terms.
        </Text>

      </ScrollView>
    </GradientScreen>
  );
}

const makeStyles = (colors) => StyleSheet.create({
  content: { padding: spacing.gutter, paddingTop: 6 },
  title: { fontSize: 24, fontWeight: '800', color: colors.text, marginBottom: 16 },
  sectionTitle: { fontSize: 16, fontWeight: '800', color: colors.goldText, marginTop: 22, marginBottom: 8 },
  paragraph: { fontSize: 14.5, lineHeight: 23, color: colors.textSoft, marginBottom: 10 },
  email: { fontSize: 14, fontWeight: '600', color: colors.goldText, marginTop: 6 },
});
